// All products data - matches schema.ts structure
export const allProducts = [
  {
    id: 1,
    name: "Advanced React Patterns",
    slug: "advanced-react-patterns",
    tagline: "Master complex React patterns and best practices",
    description:
      "Deep dive into advanced React patterns, hooks, and state management techniques for building scalable applications.",
    websiteUrl: "https://advancedreactpatterns.dev",
    tags: ["React", "JavaScript", "Web Development"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "john@example.com",
    voteCount: 145,
  },
  {
    id: 2,
    name: "CloudSync",
    slug: "cloudsync",
    tagline: "Real-time data synchronization across devices",
    description:
      "Synchronize data seamlessly across all your devices with end-to-end encryption and offline support.",
    websiteUrl: "https://cloudsync.example.com",
    tags: ["Cloud", "SaaS", "Sync"],
    createdAt: new Date("2024-01-18"),
    approvedAt: new Date("2024-01-19"),
    status: "approved" as const,
    submittedBy: "mike@example.com",
    voteCount: 92,
  },
  {
    id: 3,
    name: "DesignSystem UI",
    slug: "designsystem-ui",
    tagline: "Component library for rapid UI development",
    description:
      "Comprehensive design system with accessible components, documentation, and Figma integration for developers and designers.",
    websiteUrl: "https://designsystemui.example.com",
    tags: ["Design", "Developer Tools", "UI"],
    createdAt: new Date("2024-01-20"),
    approvedAt: new Date("2024-01-21"),
    status: "approved" as const,
    submittedBy: "alex@example.com",
    voteCount: 78,
  },
  {
    id: 4,
    name: "ConversionMax",
    slug: "conversionmax",
    tagline: "A/B testing and optimization platform",
    description:
      "Run experiments and optimize your conversion funnel with powerful A/B testing, heatmaps, and user analytics.",
    websiteUrl: "https://conversionmax.com",
    tags: ["Marketing", "Analytics", "SaaS"],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "optimize@example.com",
    voteCount: 531,
  },
  {
    id: 5,
    name: "StripeFlow",
    slug: "stripeflow",
    tagline: "Simplified payment processing and billing",
    description:
      "Streamline payment collection with intelligent retry logic, dunning management, and multi-currency support.",
    websiteUrl: "https://stripeflow.com",
    tags: ["Payments", "SaaS", "Finance"],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "payments@example.com",
    voteCount: 598,
  },
  {
    id: 6,
    name: "InsightDash",
    slug: "insightdash",
    tagline: "Business intelligence dashboard builder",
    description:
      "Build custom dashboards with SQL queries, real-time updates, and team collaboration for data-driven decision making.",
    websiteUrl: "https://insightdash.example.com",
    tags: ["BI", "Analytics", "SaaS"],
    createdAt: new Date("2024-01-28"),
    approvedAt: new Date("2024-01-29"),
    status: "approved" as const,
    submittedBy: "insights@example.com",
    voteCount: 267,
  },
  {
    id: 7,
    name: "NotificationHub",
    slug: "notificationhub",
    tagline: "Multi-channel notification delivery platform",
    description:
      "Send SMS, email, push, and in-app notifications from a single API with delivery tracking and user preferences.",
    websiteUrl: "https://notificationhub.example.com",
    tags: ["Communications", "SaaS", "APIs"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "notify@example.com",
    voteCount: 412,
  },
  {
    id: 8,
    name: "SecureVault",
    slug: "securevault",
    tagline: "Secrets and credentials management",
    description:
      "Securely store and manage API keys, passwords, and secrets with audit logs, team permissions, and rotation policies.",
    websiteUrl: "https://securevault.example.com",
    tags: ["Security", "Infrastructure", "DevOps"],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "security@example.com",
    voteCount: 521,
  },
  {
    id: 9,
    name: "Tech Leadership Bootcamp",
    slug: "tech-leadership-bootcamp",
    tagline: "Transform your engineering career into leadership",
    description:
      "Comprehensive program for engineers transitioning to leadership roles. Learn mentoring, delegation, and strategic thinking skills.",
    websiteUrl: "https://techleadershipbootcamp.com",
    tags: ["Leadership", "Career", "Engineering"],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: "pending" as const,
    submittedBy: "kulkarni.ankita09@gmail.com",
    voteCount: 367,
  },
];